version: '3'
services:
  server:
    build:
      context: ./server
      args:
        # Change according to your details
        REPOSITORY_URL: https://github.com/OpenSlides/OpenSlides.git
        BRANCH: master
        COMMIT_HASH: 14b2d33d008acdffdb71c12b953d56f4a1963389
    image: os-server
    command: bash -c "echo 'removing personal_data/var/static' &&
              rm -rf /app/personal_data/var/static &&
              echo 'removing personal_data/var/collected-static' &&
              rm -rf personal_data/var/collected-static &&
              echo 'making personal_data/var/static' &&
              mkdir -p /app/personal_data/var/static &&
              echo 'sleeping for 15 seconds...' &&
              sleep 15 &&
              echo 'running migrations' &&
              python manage.py migrate &&
              echo 'executing server' &&
              DJANGO_SETTINGS_MODULE=settings
              PYTHONPATH=personal_data/var/
              daphne -b 0.0.0.0 -p 8000 openslides.asgi:application"
              # alternatively you may use:
              #gunicorn -w 4 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker openslides.asgi:application"
    restart: always
    ports:
      - "8000:8000"
    links:
      - redis
      - postgres
    volumes:
      - "staticfiles:/app/personal_data"
      - "clientfiles:/app/openslides/static"
    networks:
      - back
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "redisdata:/data"
    networks:
      - back
  client:
    image: nginx
    restart: always
    volumes:
      - "clientfiles:/usr/share/nginx/html"
      - "./client/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "9000:80"
    environment:
      # Change according to your details
      VIRTUAL_HOST: 'localhost'
      LETSENCRYPT_HOST: 'localhost'
      LETSENCRYPT_EMAIL: 'localhost'
      LETSENCRYPT_TEST: 'true'
    depends_on:
      - server
    networks:
      - back
  proxy:
    image: jwilder/nginx-proxy
    restart: always
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "certs:/etc/nginx/certs:ro"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_conf:/etc/nginx/conf.d"
      - "nginx_dhparam:/etc/nginx/dhparam"
      - "staticfiles:/app/static:ro"
      - "./nginx/default_location:/etc/nginx/vhost.d/default_location"
      - "./nginx/htpasswd:/etc/nginx/.htpasswd"
      - "./nginx/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
      - "443:443"
    environment:
      ENABLE_IPV6: 'true'
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    depends_on:
      - server
    networks:
      - front
      - back
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "certs:/etc/nginx/certs:rw"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_conf:/etc/nginx/conf.d"
    depends_on:
      - proxy
    environment:
      NGINX_PROXY_CONTAINER: proxy
    networks:
      - back
  postgres:
    image: sameersbn/postgresql:10
    restart: always
    volumes:
      - "dbdata:/var/lib/postgresql"
    environment:
      - DB_USER=openslides
      - DB_PASS=openslides
      - DB_NAME=openslides
      - REPLICATION_USER=repluser
      - REPLICATION_PASS=repluserpass
    ports:
      - "5432:5432"
    networks:
      - front
      - back
  pg-slave:
    image: sameersbn/postgresql:10
    restart: always
    volumes:
      - "dbdata:/var/lib/postgresql"
    environment:
      - REPLICATION_MODE=slave
      - REPLICATION_SSLMODE=prefer
      - REPLICATION_HOST=127.0.0.1
      - REPLICATION_PORT=5432
      - REPLICATION_USER=repluser
      - REPLICATION_PASS=repluserpass
    networks:
      - back
  filesync:
    build: ./filesync
    image: os-filesync
    restart: always
    volumes:
      - "staticfiles:/app/static"
    environment:
      - REMOTE_MODE=MASTER
      - REMOTE_HOST=localhost
      - REMOTE_USER=openslides
      - REMOTE_PASS=openslides
    networks:
      - back
  postfix:
    build: ./postfix
    image: postfix
    restart: always
    environment:
      - maildomain=localhost
      - smtp_user=openslides:openslides
    volumes:
      - "certs:/etc/postfix/certs:ro"
    networks:
      - back
volumes:
  dbdata:
  staticfiles:
  certs:
  redisdata:
  nginx_vhost:
  nginx_html:
  nginx_conf:
  nginx_dhparam:
  clientfiles:
networks:
  front:
  back:
